#ifndef _DEFINE_H
#define _DEFINE_H

#define RANDOM(MIN, MAX) (rand() % (MAX - MIN + 1) + MIN)
#define CHOOSERANDOM(V1, V2) rand() % 2 == 0 ? V1 : V2

// SCREEN SIZE
#define WIDTH 640
#define HEIGHT 480

#define NUM_PLAYERS 4

// TYPES
#define TYPE_PADDLE_LEFT 0
#define TYPE_PADDLE_RIGHT 1
#define TYPE_PADDLE_TOP 2
#define TYPE_PADDLE_BOTTOM 3
#define TYPE_BALL_DEFAULT 4
#define TYPE_BALL_SMALL 5

// APPEARANCE
#define PADDLE_THICKNESS 20
#define PADDLE_LENGTH 200
#define PADDLE_MARGIN 10
#define PADDLE_SPEED 2

#define BALL_WIDTH 20
#define BALL_HEIGHT 20
#define BALL_SPEED 2

// CONTROL
#define CONTROL_MODE_KEYBOARD 0
#define CONTROL_MODE_MOUSE 1

#define PADDLE_LEFT_KEY_UP SDLK_w
#define PADDLE_LEFT_KEY_DOWN SDLK_s

#define PADDLE_RIGHT_KEY_UP SDLK_UP
#define PADDLE_RIGHT_KEY_DOWN SDLK_DOWN

#define PADDLE_TOP_KEY_LEFT SDLK_a
#define PADDLE_TOP_KEY_RIGHT SDLK_d

#define PADDLE_BOTTOM_KEY_LEFT SDLK_LEFT
#define PADDLE_BOTTOM_KEY_RIGHT SDLK_RIGHT

#define MOUSE_RANGE 100

#endif